import { ArrowRight, Bell, Check, CheckCheck, ChevronRight, Clock3, Filter, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { notificationCategories } from '../data/notificationData'
import { useNotifications } from '../context/NotificationContext'
import { Button, Icon } from '../components/ui'

function NotificationCard({ notification, onRead }) {
  return <article className={`notification-page-card ${notification.unread ? 'unread' : ''}`}><div className={`notification-page-icon ${notification.tone}`}><Icon name={notification.icon} size={17} /></div><div className="notification-page-main"><div className="notification-page-heading"><div><span className="eyebrow">{notification.category}</span><h2>{notification.title}</h2></div>{notification.unread && <span className="notification-unread-label">New</span>}</div><p>{notification.description}</p><div className="notification-page-footer"><span><Clock3 size={13} />{notification.timestamp}</span><div>{notification.unread && <button className="notification-read-button" onClick={() => onRead(notification.id)}><Check size={14} />Mark as read</button>}<Link to={notification.actionPath} onClick={() => onRead(notification.id)} className="notification-action">{notification.actionLabel}<ChevronRight size={14} /></Link></div></div></div></article>
}

export default function NotificationsPage() {
  const { notifications, unreadCount, markAsRead, markAllAsRead } = useNotifications()
  const [activeCategory, setActiveCategory] = useState('All')
  const filteredNotifications = useMemo(() => activeCategory === 'All' ? notifications : notifications.filter((notification) => notification.category === activeCategory), [activeCategory, notifications])
  return <div className="notifications-page"><header className="notifications-page-heading"><div><span className="eyebrow accent-eyebrow">Workspace updates</span><h1>Notifications</h1><p>Stay close to the opportunities, conversations and next steps that matter.</p></div><div className="notifications-summary"><strong>{unreadCount}</strong><span>unread updates</span></div></header><div className="notifications-toolbar"><nav className="notification-tabs" aria-label="Notification categories">{notificationCategories.map((category) => <button className={activeCategory === category ? 'active' : ''} onClick={() => setActiveCategory(category)} key={category} aria-current={activeCategory === category ? 'page' : undefined}>{category}<span>{category === 'All' ? notifications.length : notifications.filter((notification) => notification.category === category).length}</span></button>)}</nav><Button variant="ghost" icon={CheckCheck} onClick={markAllAsRead} disabled={unreadCount === 0}>Mark all as read</Button></div><div className="notifications-list-heading"><span>{filteredNotifications.length} {filteredNotifications.length === 1 ? 'notification' : 'notifications'}</span><span className="notifications-live"><Bell size={13} /> Synced across your workspace</span></div>{filteredNotifications.length > 0 ? <div className="notifications-list">{filteredNotifications.map((notification) => <NotificationCard key={notification.id} notification={notification} onRead={markAsRead} />)}</div> : <div className="notifications-empty"><div><Filter size={22} /></div><h2>No notifications in this category</h2><p>New updates will appear here as your workspace becomes active.</p><button className="button button-secondary" onClick={() => setActiveCategory('All')}>View all notifications</button></div>}</div>
}
