import { ArrowLeft, ArrowRight, BriefcaseBusiness, CalendarDays, CheckCircle2, Clock3, MapPin, Share2, SlidersHorizontal, Sparkles, UsersRound } from 'lucide-react'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { opportunityData } from '../data/opportunityData'
import { Button } from '../components/ui'

export default function OpportunityDetail() {
  const { opportunityId } = useParams()
  const opportunity = opportunityData.find((item) => item.id === opportunityId)
  const [applied, setApplied] = useState(false)
  if (!opportunity) return <div className="opportunity-detail"><Link to="/opportunities" className="back-link"><ArrowLeft size={16} /> Back to opportunities</Link><div className="opportunity-empty"><div><SearchFallback /></div><h2>Opportunity not found</h2><p>This listing may have closed or moved.</p><Link className="button button-secondary" to="/opportunities">Explore opportunities</Link></div></div>
  return <div className="opportunity-detail"><Link to="/opportunities" className="back-link"><ArrowLeft size={16} /> Back to opportunities</Link><div className="detail-layout"><main><header className="detail-hero"><div className={`detail-logo ${opportunity.tone}`}>{opportunity.initials}</div><div className="detail-heading"><span className="eyebrow">{opportunity.organizationType}</span><h1>{opportunity.title}</h1><p>{opportunity.organization}</p><div className="detail-tags"><span className={`result-type ${opportunity.type.toLowerCase()}`}><BriefcaseBusiness size={13} />{opportunity.type}</span><span><MapPin size={14} />{opportunity.location}</span><span><SlidersHorizontal size={14} />{opportunity.workMode}</span></div></div><button className="share-button" aria-label="Share opportunity"><Share2 size={18} /></button></header><section className="detail-section"><span className="eyebrow">The opportunity</span><h2>Make an impact with {opportunity.organization}.</h2><p>{opportunity.description}</p></section><section className="detail-section"><span className="eyebrow">What you will do</span><ul className="detail-list">{opportunity.responsibilities.map((item) => <li key={item}><CheckCircle2 size={16} />{item}</li>)}</ul></section><section className="detail-section"><span className="eyebrow">What you bring</span><ul className="detail-list">{opportunity.requirements.map((item) => <li key={item}><CheckCircle2 size={16} />{item}</li>)}</ul></section></main><aside className="detail-sidebar"><div className="detail-apply-card"><span className="eyebrow">Ready to apply?</span><h2>{applied ? 'Application started.' : 'Your next move starts here.'}</h2><p>{applied ? 'This prototype has saved your interest locally for this session.' : 'Review the details, then take the first step toward this opportunity.'}</p><Button icon={applied ? CheckCircle2 : ArrowRight} onClick={() => setApplied(true)}>{applied ? 'Application saved' : 'Apply now'}</Button><span className="detail-disclaimer">Mock application flow · no backend connection</span></div><div className="detail-facts"><div><Clock3 size={16} /><span>Duration<strong>{opportunity.duration}</strong></span></div><div><Sparkles size={16} /><span>Compensation<strong>{opportunity.stipend}</strong></span></div><div><CalendarDays size={16} /><span>Posted<strong>{opportunity.postedLabel.replace('Posted ', '')}</strong></span></div><div><UsersRound size={16} /><span>Opportunity type<strong>{opportunity.type}</strong></span></div></div><div className="detail-skills"><span className="eyebrow">Required skills</span><div>{opportunity.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div></aside></div></div>
}

function SearchFallback() { return <Sparkles size={24} /> }
